// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.0
// source: github.com/Microsoft/hcsshim/pkg/extendedtask/extendedtask.proto

package extendedtask

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeProcessorInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ComputeProcessorInfoRequest) Reset() {
	*x = ComputeProcessorInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeProcessorInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeProcessorInfoRequest) ProtoMessage() {}

func (x *ComputeProcessorInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeProcessorInfoRequest.ProtoReflect.Descriptor instead.
func (*ComputeProcessorInfoRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeProcessorInfoRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ComputeProcessorInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ComputeProcessorInfoResponse) Reset() {
	*x = ComputeProcessorInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeProcessorInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeProcessorInfoResponse) ProtoMessage() {}

func (x *ComputeProcessorInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeProcessorInfoResponse.ProtoReflect.Descriptor instead.
func (*ComputeProcessorInfoResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeProcessorInfoResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateSocketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerID string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
}

func (x *CreateSocketRequest) Reset() {
	*x = CreateSocketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSocketRequest) ProtoMessage() {}

func (x *CreateSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSocketRequest.ProtoReflect.Descriptor instead.
func (*CreateSocketRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSocketRequest) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

type CreateSocketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerID string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Types that are assignable to ConnectionInfo:
	//
	//	*CreateSocketResponse_HvSocket
	//	*CreateSocketResponse_UnixSocket
	ConnectionInfo isCreateSocketResponse_ConnectionInfo `protobuf_oneof:"connection_info"`
}

func (x *CreateSocketResponse) Reset() {
	*x = CreateSocketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSocketResponse) ProtoMessage() {}

func (x *CreateSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSocketResponse.ProtoReflect.Descriptor instead.
func (*CreateSocketResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSocketResponse) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (m *CreateSocketResponse) GetConnectionInfo() isCreateSocketResponse_ConnectionInfo {
	if m != nil {
		return m.ConnectionInfo
	}
	return nil
}

func (x *CreateSocketResponse) GetHvSocket() *HvSocket {
	if x, ok := x.GetConnectionInfo().(*CreateSocketResponse_HvSocket); ok {
		return x.HvSocket
	}
	return nil
}

func (x *CreateSocketResponse) GetUnixSocket() *UnixSocket {
	if x, ok := x.GetConnectionInfo().(*CreateSocketResponse_UnixSocket); ok {
		return x.UnixSocket
	}
	return nil
}

type isCreateSocketResponse_ConnectionInfo interface {
	isCreateSocketResponse_ConnectionInfo()
}

type CreateSocketResponse_HvSocket struct {
	HvSocket *HvSocket `protobuf:"bytes,2,opt,name=hv_socket,json=hvSocket,proto3,oneof"`
}

type CreateSocketResponse_UnixSocket struct {
	UnixSocket *UnixSocket `protobuf:"bytes,3,opt,name=unix_socket,json=unixSocket,proto3,oneof"`
}

func (*CreateSocketResponse_HvSocket) isCreateSocketResponse_ConnectionInfo() {}

func (*CreateSocketResponse_UnixSocket) isCreateSocketResponse_ConnectionInfo() {}

type HvSocket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VmID      string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ServiceID string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
}

func (x *HvSocket) Reset() {
	*x = HvSocket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HvSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HvSocket) ProtoMessage() {}

func (x *HvSocket) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HvSocket.ProtoReflect.Descriptor instead.
func (*HvSocket) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescGZIP(), []int{4}
}

func (x *HvSocket) GetVmID() string {
	if x != nil {
		return x.VmID
	}
	return ""
}

func (x *HvSocket) GetServiceID() string {
	if x != nil {
		return x.ServiceID
	}
	return ""
}

type UnixSocket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VmID       string `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	SocketPath string `protobuf:"bytes,2,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
}

func (x *UnixSocket) Reset() {
	*x = UnixSocket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnixSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocket) ProtoMessage() {}

func (x *UnixSocket) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocket.ProtoReflect.Descriptor instead.
func (*UnixSocket) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescGZIP(), []int{5}
}

func (x *UnixSocket) GetVmID() string {
	if x != nil {
		return x.VmID
	}
	return ""
}

func (x *UnixSocket) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

var File_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto protoreflect.FileDescriptor

var file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDesc = []byte{
	0x0a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x68, 0x63, 0x73, 0x73, 0x68, 0x69, 0x6d, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x74, 0x61, 0x73, 0x6b, 0x2f,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x34, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49,
	0x64, 0x22, 0xa6, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x09, 0x68, 0x76, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x48, 0x76, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x00, 0x52, 0x08, 0x68,
	0x76, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x78, 0x5f,
	0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55,
	0x6e, 0x69, 0x78, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x75, 0x6e, 0x69,
	0x78, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x3e, 0x0a, 0x08, 0x48, 0x76,
	0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x0a, 0x55, 0x6e,
	0x69, 0x78, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x32, 0xa4,
	0x01, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x55, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescOnce sync.Once
	file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescData = file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDesc
)

func file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescGZIP() []byte {
	file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescOnce.Do(func() {
		file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescData)
	})
	return file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDescData
}

var file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_goTypes = []any{
	(*ComputeProcessorInfoRequest)(nil),  // 0: ComputeProcessorInfoRequest
	(*ComputeProcessorInfoResponse)(nil), // 1: ComputeProcessorInfoResponse
	(*CreateSocketRequest)(nil),          // 2: CreateSocketRequest
	(*CreateSocketResponse)(nil),         // 3: CreateSocketResponse
	(*HvSocket)(nil),                     // 4: HvSocket
	(*UnixSocket)(nil),                   // 5: UnixSocket
}
var file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_depIdxs = []int32{
	4, // 0: CreateSocketResponse.hv_socket:type_name -> HvSocket
	5, // 1: CreateSocketResponse.unix_socket:type_name -> UnixSocket
	0, // 2: ExtendedTask.ComputeProcessorInfo:input_type -> ComputeProcessorInfoRequest
	2, // 3: ExtendedTask.CreateSocket:input_type -> CreateSocketRequest
	1, // 4: ExtendedTask.ComputeProcessorInfo:output_type -> ComputeProcessorInfoResponse
	3, // 5: ExtendedTask.CreateSocket:output_type -> CreateSocketResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_init() }
func file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_init() {
	if File_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ComputeProcessorInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ComputeProcessorInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSocketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSocketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*HvSocket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UnixSocket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateSocketResponse_HvSocket)(nil),
		(*CreateSocketResponse_UnixSocket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_goTypes,
		DependencyIndexes: file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_depIdxs,
		MessageInfos:      file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_msgTypes,
	}.Build()
	File_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto = out.File
	file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_rawDesc = nil
	file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_goTypes = nil
	file_github_com_Microsoft_hcsshim_pkg_extendedtask_extendedtask_proto_depIdxs = nil
}
