on: push
name: Build & Release
env:
  GO_VERSION: "1.18.x"
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go build ./cmd/dmverity-vhd
      - run: go build ./cmd/dmverity-vhd
        env:
          GOOS: windows
          GOARCH: amd64
      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            dmverity-vhd
            dmverity-vhd.exe
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: binaries
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dmverity-vhd
            dmverity-vhd.exe
